---
- name: Configurar server Java
  hosts: app01

  user: vagrant
  become: yes

  vars_files:
    vars/main.yaml
  vars:
    - dbhost: "db01"
    - dbname: "notes"
    - dbusername: "notesapp"
    - dbpassword: 1234

  tasks:
    - name: Configurar hosts
      lineinfile:
        dest: /etc/hosts
        state: present
        line: "{{item}}"
      with_items:
        - "{{networkbaseip}}.2 control-node"
        - "{{networkbaseip}}.3 app01"
        - "{{networkbaseip}}.4 db01"
    - name: Adicionar grupo app
      group:
        name: app
    - name: Adicionar usuario app
      user:
        name: app
        group: app
        uid: 500
    - name: Criar pasta da aplicacao
      file:
        path: /opt/notes/
        state: directory
        owner: app
        group: app
    - name: Clonar repositorio
      git:
        repo: "https://github.com/callicoder/spring-boot-mysql-rest-api-tutorial.git"
        dest: /opt/notes
        clone: yes
        force: yes
    - name: Copiar arquivo de template
      template:
        src: application.properties
        dest: /opt/notes/src/main/resources/application.properties
    - name: Instalar java jdk-11
      apt: 
        name: openjdk-11-jdk-headless
        state: latest
    - name: Setando versao correta do java
      community.general.alternatives:
        name: java
        path: /usr/lib/jvm/java-1.11-openjdk-amd64/jre/bin/java
    - name: Instalar maven
      apt:
        name: maven
        state: latest
    - name: Gerar pacote
      become: yes
      become_user: app
      command: mvn -f /opt/notes/pom.xml package
    - name: Registrar versao do aplicativo
      shell:
        cmd: mvn -o -q -Dexec.executable=echo -Dexec.args="${project.version}"
        chdir: /opt/notes/
      register: appversion
    - name: Configurar servicos
      template:
        src: notes.service
        dest: /etc/systemd/system/notes.service
        notify: reload daemon
    - name: Iniciar o servico
      service:
        name: notes
        state: restarted

  roles:
    - configuracao-so

  handlers:
    - name: reload daemon
      systemd:
        daemon_reexec: yes
