
Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"
    config.vm.hostname = "db01"
    config.vm.network "private_network", ip:"192.167.1.4"
    config.vm.network "forwarded_port", guest: 3306, host: 3306
    config.vm.provision "file", source: "../control-node/ssh/id_rsa.pub", destination: "/tmp/"
    config.vm.provision "shell", inline: "cat /tmp/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys && chmod +rw /home/vagrant/.ssh/authorized_keys "
end