
Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/xenial64"
    config.vm.hostname = "db01"
    config.vm.network "private_network", ip:"192.167.1.4"
    config.vm.network "forwarded_port", guest: 3306, host: 3306
  end
  