
Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"
    config.vm.hostname = "app01"
    config.vm.network "private_network", ip:"192.167.1.3"
    config.vm.network "forwarded_port", guest: 8080, host: 8080
    config.vm.provision "file", source: "../control-node/ssh/id_rsa.pub", destination: "/tmp/"
    config.vm.provision "shell", inline: "cat /tmp/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys"
  end