
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.hostname = "control-node"
  config.vm.network "private_network", ip:"192.167.1.2"
  config.vm.synced_folder ".", "/vagrant", "type": "nfs"
  config.vm.provision "shell", path: "provision.sh"
end
